# ref: https://github.com/rxhanson/Rectangle/blob/master/.github/workflows/build.yml

name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
      - '*.png'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Get Version Number
      run: echo "VERSION=$(deno run version.ts)" >> "$GITHUB_ENV"
    - name: Compile for ${{ matrix.target }}
      run: deno task compile --target ${{ matrix.target }}
    - name: Compress Binary
      run: tar -zcvf genelic-v${{ env.VERSION }}-${{ matrix.target }}.tar.gz bin/genelic
    - name: Upload
      if: github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: TAR
        path: genelic-v${{ env.VERSION }}-${{ matrix.target }}.tar.gz
    - name: Create Release Draft
      if: github.ref == 'refs/heads/main'
      id: create-draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: v${{ env.VERSION }}
        tag: v${{ env.VERSION }}
    - name: Upload Binary
      if: github.ref == 'refs/heads/main'
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-draft.outputs.upload_url }}
        asset_path: $genelic-v${{ env.VERSION }}-${{ matrix.target }}.tar.gz
        overwrite: true
