name: Prepare Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - '*.png'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Get Version Number
      run: echo "VERSION=$(deno task run -V)" >> "$GITHUB_ENV"
    - name: Create Release Draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: v${{ env.VERSION }}
        tag: v${{ env.VERSION }}
