name: Prepare Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - '*.png'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get Version Number
      run: echo "VERSION=$(sed -n 's/.*"\([^"]*\)".*/\1/p' version.ts)" >> "$GITHUB_ENV"
    - name: Create Release Draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.VERSION }}
        tag: ${{ env.VERSION }}
